from ._spatial_calcs import calculate_local_counts, calculate_local_means
from ._spatial_window import create_spatial_windows

from argparse import ArgumentParser, Namespace
import dask.dataframe as dd
from functools import reduce
from glob import glob
import pandas as pd
from pathlib import Path
import os
from shutil import rmtree

def get_cli_args() -> Namespace:
    parser = ArgumentParser()
    parser.add_argument("--input-folder", help="Input folder", type=str, required=True)
    return parser.parse_args()

def concat_dfs(in_dir: str, out_path: str) -> None:
    paths = glob(os.path.join(in_dir, "*.csv"))
    dfs = [pd.read_csv(path) for path in paths]
    df = pd.concat(dfs, axis=0)
    df.to_csv(out_path, index=False)

if __name__=="__main__":
    args = get_cli_args()
    full_path = str(Path(args.input_folder).resolve())
    spatial_temp_path = os.path.join(full_path, "spatial_temp")
    os.mkdir(spatial_temp_path)
    spatial_windows_path = os.path.join(spatial_temp_path, "spatial_windows")
    os.mkdir(spatial_windows_path)
    data = dd.read_csv(os.path.join(full_path, "morphology.csv"))
    create_spatial_windows(data, spatial_windows_path)
    local_counts_path_25 = os.path.join(spatial_temp_path, "local_counts_25")
    local_counts_path_50 = os.path.join(spatial_temp_path, "local_counts_50")
    local_counts_path_75 = os.path.join(spatial_temp_path, "local_counts_75")
    local_counts_path_100 = os.path.join(spatial_temp_path, "local_counts_100")
    local_counts_path_125 = os.path.join(spatial_temp_path, "local_counts_125")
    local_counts_path_150 = os.path.join(spatial_temp_path, "local_counts_150")
    local_counts_path_175 = os.path.join(spatial_temp_path, "local_counts_175")
    local_counts_path_200 = os.path.join(spatial_temp_path, "local_counts_200")
    os.mkdir(local_counts_path_25)
    os.mkdir(local_counts_path_50)
    os.mkdir(local_counts_path_75)
    os.mkdir(local_counts_path_100)
    os.mkdir(local_counts_path_125)
    os.mkdir(local_counts_path_150)
    os.mkdir(local_counts_path_175)
    os.mkdir(local_counts_path_200)
    
    local_means1_path_25 = os.path.join(spatial_temp_path, "local_means_1_25")
    local_means1_path_50 = os.path.join(spatial_temp_path, "local_means_1_50")
    local_means1_path_75 = os.path.join(spatial_temp_path, "local_means_1_75")
    local_means1_path_100 = os.path.join(spatial_temp_path, "local_means_1_100")
    local_means1_path_125 = os.path.join(spatial_temp_path, "local_means_1_125")
    local_means1_path_150 = os.path.join(spatial_temp_path, "local_means_1_150")
    local_means1_path_175 = os.path.join(spatial_temp_path, "local_means_1_175")
    local_means1_path_200 = os.path.join(spatial_temp_path, "local_means_1_200")
    os.mkdir(local_means1_path_25)
    os.mkdir(local_means1_path_50)
    os.mkdir(local_means1_path_75)
    os.mkdir(local_means1_path_100)
    os.mkdir(local_means1_path_125)
    os.mkdir(local_means1_path_150)
    os.mkdir(local_means1_path_175)
    os.mkdir(local_means1_path_200)
    
    local_means2_path_25 = os.path.join(spatial_temp_path, "local_means_2_25")
    local_means2_path_50 = os.path.join(spatial_temp_path, "local_means_2_50")
    local_means2_path_75 = os.path.join(spatial_temp_path, "local_means_2_75")
    local_means2_path_100 = os.path.join(spatial_temp_path, "local_means_2_100")
    local_means2_path_125 = os.path.join(spatial_temp_path, "local_means_2_125")
    local_means2_path_150 = os.path.join(spatial_temp_path, "local_means_2_150")
    local_means2_path_175 = os.path.join(spatial_temp_path, "local_means_2_175")
    local_means2_path_200 = os.path.join(spatial_temp_path, "local_means_2_200")
    os.mkdir(local_means2_path_25)
    os.mkdir(local_means2_path_50)
    os.mkdir(local_means2_path_75)
    os.mkdir(local_means2_path_100)
    os.mkdir(local_means2_path_125)
    os.mkdir(local_means2_path_150)
    os.mkdir(local_means2_path_175)
    os.mkdir(local_means2_path_200)
    
    local_means3_path_25 = os.path.join(spatial_temp_path, "local_means_3_25")
    local_means3_path_50 = os.path.join(spatial_temp_path, "local_means_3_50")
    local_means3_path_75 = os.path.join(spatial_temp_path, "local_means_3_75")
    local_means3_path_100 = os.path.join(spatial_temp_path, "local_means_3_100")
    local_means3_path_125 = os.path.join(spatial_temp_path, "local_means_3_125")
    local_means3_path_150 = os.path.join(spatial_temp_path, "local_means_3_150")
    local_means3_path_175 = os.path.join(spatial_temp_path, "local_means_3_175")
    local_means3_path_200 = os.path.join(spatial_temp_path, "local_means_3_200")
    os.mkdir(local_means3_path_25)
    os.mkdir(local_means3_path_50)
    os.mkdir(local_means3_path_75)
    os.mkdir(local_means3_path_100)
    os.mkdir(local_means3_path_125)
    os.mkdir(local_means3_path_150)
    os.mkdir(local_means3_path_175)
    os.mkdir(local_means3_path_200)
    
    local_means4_path_25 = os.path.join(spatial_temp_path, "local_means_4_25")
    local_means4_path_50 = os.path.join(spatial_temp_path, "local_means_4_50")
    local_means4_path_75 = os.path.join(spatial_temp_path, "local_means_4_75")
    local_means4_path_100 = os.path.join(spatial_temp_path, "local_means_4_100")
    local_means4_path_125 = os.path.join(spatial_temp_path, "local_means_4_125")
    local_means4_path_150 = os.path.join(spatial_temp_path, "local_means_4_150")
    local_means4_path_175 = os.path.join(spatial_temp_path, "local_means_4_175")
    local_means4_path_200 = os.path.join(spatial_temp_path, "local_means_4_200")
    os.mkdir(local_means4_path_25)
    os.mkdir(local_means4_path_50)
    os.mkdir(local_means4_path_75)
    os.mkdir(local_means4_path_100)
    os.mkdir(local_means4_path_125)
    os.mkdir(local_means4_path_150)
    os.mkdir(local_means4_path_175)
    os.mkdir(local_means4_path_200)
    
    local_means5_path_25 = os.path.join(spatial_temp_path, "local_means_5_25")
    local_means5_path_50 = os.path.join(spatial_temp_path, "local_means_5_50")
    local_means5_path_75 = os.path.join(spatial_temp_path, "local_means_5_75")
    local_means5_path_100 = os.path.join(spatial_temp_path, "local_means_5_100")
    local_means5_path_125 = os.path.join(spatial_temp_path, "local_means_5_125")
    local_means5_path_150 = os.path.join(spatial_temp_path, "local_means_5_150")
    local_means5_path_175 = os.path.join(spatial_temp_path, "local_means_5_175")
    local_means5_path_200 = os.path.join(spatial_temp_path, "local_means_5_200")
    os.mkdir(local_means5_path_25)
    os.mkdir(local_means5_path_50)
    os.mkdir(local_means5_path_75)
    os.mkdir(local_means5_path_100)
    os.mkdir(local_means5_path_125)
    os.mkdir(local_means5_path_150)
    os.mkdir(local_means5_path_175)
    os.mkdir(local_means5_path_200)
    spatial_window_dfs = [pd.read_csv(path) for path in glob(os.path.join(spatial_windows_path, "*.csv"))]
    for i, window in enumerate(spatial_window_dfs):
        calculate_local_counts(window, os.path.join(local_counts_path_25, f"local_counts{i}.csv"), distance_threshold=25)
        calculate_local_counts(window, os.path.join(local_counts_path_50, f"local_counts{i}.csv"), distance_threshold=50)
        calculate_local_counts(window, os.path.join(local_counts_path_75, f"local_counts{i}.csv"), distance_threshold=75)
        calculate_local_counts(window, os.path.join(local_counts_path_100, f"local_counts{i}.csv"), distance_threshold=100)
        calculate_local_counts(window, os.path.join(local_counts_path_125, f"local_counts{i}.csv"), distance_threshold=125)
        calculate_local_counts(window, os.path.join(local_counts_path_150, f"local_counts{i}.csv"), distance_threshold=150)
        calculate_local_counts(window, os.path.join(local_counts_path_175, f"local_counts{i}.csv"), distance_threshold=175)
        calculate_local_counts(window, os.path.join(local_counts_path_200, f"local_counts{i}.csv"), distance_threshold=200)
        
        calculate_local_means(window, os.path.join(local_means1_path_25, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Area", distance_threshold=25)
        calculate_local_means(window, os.path.join(local_means1_path_50, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Area", distance_threshold=50)
        calculate_local_means(window, os.path.join(local_means1_path_75, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Area", distance_threshold=75)
        calculate_local_means(window, os.path.join(local_means1_path_100, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Area", distance_threshold=100)
        calculate_local_means(window, os.path.join(local_means1_path_125, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Area", distance_threshold=125)
        calculate_local_means(window, os.path.join(local_means1_path_150, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Area", distance_threshold=150)
        calculate_local_means(window, os.path.join(local_means1_path_175, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Area", distance_threshold=175)
        calculate_local_means(window, os.path.join(local_means1_path_200, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Area", distance_threshold=200)
        
        calculate_local_means(window, os.path.join(local_means2_path_25, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_AxisMinorLength", distance_threshold=25)
        calculate_local_means(window, os.path.join(local_means2_path_50, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_AxisMinorLength", distance_threshold=50)
        calculate_local_means(window, os.path.join(local_means2_path_75, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_AxisMinorLength", distance_threshold=75)
        calculate_local_means(window, os.path.join(local_means2_path_100, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_AxisMinorLength", distance_threshold=100)
        calculate_local_means(window, os.path.join(local_means2_path_125, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_AxisMinorLength", distance_threshold=125)
        calculate_local_means(window, os.path.join(local_means2_path_150, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_AxisMinorLength", distance_threshold=150)
        calculate_local_means(window, os.path.join(local_means2_path_175, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_AxisMinorLength", distance_threshold=175)
        calculate_local_means(window, os.path.join(local_means2_path_200, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_AxisMinorLength", distance_threshold=200)
        
        calculate_local_means(window, os.path.join(local_means3_path_25, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Eccentricity", distance_threshold=25)
        calculate_local_means(window, os.path.join(local_means3_path_50, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Eccentricity", distance_threshold=50)
        calculate_local_means(window, os.path.join(local_means3_path_75, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Eccentricity", distance_threshold=75)
        calculate_local_means(window, os.path.join(local_means3_path_100, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Eccentricity", distance_threshold=100)
        calculate_local_means(window, os.path.join(local_means3_path_125, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Eccentricity", distance_threshold=125)
        calculate_local_means(window, os.path.join(local_means3_path_150, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Eccentricity", distance_threshold=150)
        calculate_local_means(window, os.path.join(local_means3_path_175, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Eccentricity", distance_threshold=175)
        calculate_local_means(window, os.path.join(local_means3_path_200, f"local_counts{i}.csv"), feature_name="AreaShape_Nuclei_Mask_Eccentricity", distance_threshold=200)
        
        calculate_local_means(window, os.path.join(local_means4_path_25, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MeanIntensity", distance_threshold=25)
        calculate_local_means(window, os.path.join(local_means4_path_50, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MeanIntensity", distance_threshold=50)
        calculate_local_means(window, os.path.join(local_means4_path_75, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MeanIntensity", distance_threshold=75)
        calculate_local_means(window, os.path.join(local_means4_path_100, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MeanIntensity", distance_threshold=100)
        calculate_local_means(window, os.path.join(local_means4_path_125, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MeanIntensity", distance_threshold=125)
        calculate_local_means(window, os.path.join(local_means4_path_150, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MeanIntensity", distance_threshold=150)
        calculate_local_means(window, os.path.join(local_means4_path_175, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MeanIntensity", distance_threshold=175)
        calculate_local_means(window, os.path.join(local_means4_path_200, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MeanIntensity", distance_threshold=200)
        
        calculate_local_means(window, os.path.join(local_means5_path_25, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MedianIntensity", distance_threshold=25)
        calculate_local_means(window, os.path.join(local_means5_path_50, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MedianIntensity", distance_threshold=50)
        calculate_local_means(window, os.path.join(local_means5_path_75, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MedianIntensity", distance_threshold=75)
        calculate_local_means(window, os.path.join(local_means5_path_100, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MedianIntensity", distance_threshold=100)
        calculate_local_means(window, os.path.join(local_means5_path_125, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MedianIntensity", distance_threshold=125)
        calculate_local_means(window, os.path.join(local_means5_path_150, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MedianIntensity", distance_threshold=150)
        calculate_local_means(window, os.path.join(local_means5_path_175, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MedianIntensity", distance_threshold=175)
        calculate_local_means(window, os.path.join(local_means5_path_200, f"local_counts{i}.csv"), feature_name="Intensity_Cytoplasm_Secondary_MedianIntensity", distance_threshold=200)
    concat_dfs(local_counts_path_25, os.path.join(spatial_temp_path, "local_counts_25.csv"))
    concat_dfs(local_counts_path_50, os.path.join(spatial_temp_path, "local_counts_50.csv"))
    concat_dfs(local_counts_path_75, os.path.join(spatial_temp_path, "local_counts_75.csv"))
    concat_dfs(local_counts_path_100, os.path.join(spatial_temp_path, "local_counts_100.csv"))
    concat_dfs(local_counts_path_125, os.path.join(spatial_temp_path, "local_counts_125.csv"))
    concat_dfs(local_counts_path_150, os.path.join(spatial_temp_path, "local_counts_150.csv"))
    concat_dfs(local_counts_path_175, os.path.join(spatial_temp_path, "local_counts_175.csv"))
    concat_dfs(local_counts_path_200, os.path.join(spatial_temp_path, "local_counts_200.csv"))
    
    concat_dfs(local_means1_path_25, os.path.join(spatial_temp_path, "local_means1_25.csv"))
    concat_dfs(local_means1_path_50, os.path.join(spatial_temp_path, "local_means1_50.csv"))
    concat_dfs(local_means1_path_75, os.path.join(spatial_temp_path, "local_means1_75.csv"))
    concat_dfs(local_means1_path_100, os.path.join(spatial_temp_path, "local_means1_100.csv"))
    concat_dfs(local_means1_path_125, os.path.join(spatial_temp_path, "local_means1_125.csv"))
    concat_dfs(local_means1_path_150, os.path.join(spatial_temp_path, "local_means1_150.csv"))
    concat_dfs(local_means1_path_175, os.path.join(spatial_temp_path, "local_means1_175.csv"))
    concat_dfs(local_means1_path_200, os.path.join(spatial_temp_path, "local_means1_200.csv"))
    
    concat_dfs(local_means2_path_25, os.path.join(spatial_temp_path, "local_means2_25.csv"))
    concat_dfs(local_means2_path_50, os.path.join(spatial_temp_path, "local_means2_50.csv"))
    concat_dfs(local_means2_path_75, os.path.join(spatial_temp_path, "local_means2_75.csv"))
    concat_dfs(local_means2_path_100, os.path.join(spatial_temp_path, "local_means2_100.csv"))
    concat_dfs(local_means2_path_125, os.path.join(spatial_temp_path, "local_means2_125.csv"))
    concat_dfs(local_means2_path_150, os.path.join(spatial_temp_path, "local_means2_150.csv"))
    concat_dfs(local_means2_path_175, os.path.join(spatial_temp_path, "local_means2_175.csv"))
    concat_dfs(local_means2_path_200, os.path.join(spatial_temp_path, "local_means2_200.csv"))
    
    concat_dfs(local_means3_path_25, os.path.join(spatial_temp_path, "local_means3_25.csv"))
    concat_dfs(local_means3_path_50, os.path.join(spatial_temp_path, "local_means3_50.csv"))
    concat_dfs(local_means3_path_75, os.path.join(spatial_temp_path, "local_means3_75.csv"))
    concat_dfs(local_means3_path_100, os.path.join(spatial_temp_path, "local_means3_100.csv"))
    concat_dfs(local_means3_path_125, os.path.join(spatial_temp_path, "local_means3_125.csv"))
    concat_dfs(local_means3_path_150, os.path.join(spatial_temp_path, "local_means3_150.csv"))
    concat_dfs(local_means3_path_175, os.path.join(spatial_temp_path, "local_means3_175.csv"))
    concat_dfs(local_means3_path_200, os.path.join(spatial_temp_path, "local_means3_200.csv"))
    
    concat_dfs(local_means4_path_25, os.path.join(spatial_temp_path, "local_means4_25.csv"))
    concat_dfs(local_means4_path_50, os.path.join(spatial_temp_path, "local_means4_50.csv"))
    concat_dfs(local_means4_path_75, os.path.join(spatial_temp_path, "local_means4_75.csv"))
    concat_dfs(local_means4_path_100, os.path.join(spatial_temp_path, "local_means4_100.csv"))
    concat_dfs(local_means4_path_125, os.path.join(spatial_temp_path, "local_means4_125.csv"))
    concat_dfs(local_means4_path_150, os.path.join(spatial_temp_path, "local_means4_150.csv"))
    concat_dfs(local_means4_path_175, os.path.join(spatial_temp_path, "local_means4_175.csv"))
    concat_dfs(local_means4_path_200, os.path.join(spatial_temp_path, "local_means4_200.csv"))
    
    concat_dfs(local_means5_path_25, os.path.join(spatial_temp_path, "local_means5_25.csv"))
    concat_dfs(local_means5_path_50, os.path.join(spatial_temp_path, "local_means5_50.csv"))
    concat_dfs(local_means5_path_75, os.path.join(spatial_temp_path, "local_means5_75.csv"))
    concat_dfs(local_means5_path_100, os.path.join(spatial_temp_path, "local_means5_100.csv"))
    concat_dfs(local_means5_path_125, os.path.join(spatial_temp_path, "local_means5_125.csv"))
    concat_dfs(local_means5_path_150, os.path.join(spatial_temp_path, "local_means5_150.csv"))
    concat_dfs(local_means5_path_175, os.path.join(spatial_temp_path, "local_means5_175.csv"))
    concat_dfs(local_means5_path_200, os.path.join(spatial_temp_path, "local_means5_200.csv"))
    spatial_dfs = glob(os.path.join(spatial_temp_path, "*.csv"))
    spatial_dfs = [pd.read_csv(path) for path in spatial_dfs]
    out_df = reduce(lambda left, right: pd.merge(left, right, on="Meta_Global_Mask_Label", how='left'), spatial_dfs)
    out_df.to_csv(os.path.join(full_path, "spatial.csv"), index=False)
    rmtree(spatial_temp_path)
        
